services:
  # Spring Boot Application Service
  firestore_emulator:
    image: mtlynch/firestore-emulator
    environment:
      - FIRESTORE_PROJECT_ID=dummy-project-id
      - PORT=8200
    ports:
      - 8200:8200
    networks:
      - spring-network
  property-backend:
    container_name: property-backend
    image: com/group/property-backend:latest
    ports:
      - "8081:8081"
  gm-property-frontend:
    container_name: gm-property-frontend
    image: com/group/gm-property-frontend:latest
    ports:
      - "3000:3000"
