/* tslint:disable */
/* eslint-disable */
/**
 * GM Parking API
 * OpenAPI-Spezifikation der GM Parking-API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Die Auslastung eines Parkhauses
 * @export
 * @interface Occupancy
 */
export interface Occupancy {
    /**
     * 
     * @type {number}
     * @memberof Occupancy
     */
    spaces?: number;
    /**
     * 
     * @type {number}
     * @memberof Occupancy
     */
    used?: number;
}

/**
 * Check if a given object implements the Occupancy interface.
 */
export function instanceOfOccupancy(value: object): value is Occupancy {
    return true;
}

export function OccupancyFromJSON(json: any): Occupancy {
    return OccupancyFromJSONTyped(json, false);
}

export function OccupancyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Occupancy {
    if (json == null) {
        return json;
    }
    return {
        
        'spaces': json['spaces'] == null ? undefined : json['spaces'],
        'used': json['used'] == null ? undefined : json['used'],
    };
}

  export function OccupancyToJSON(json: any): Occupancy {
      return OccupancyToJSONTyped(json, false);
  }

  export function OccupancyToJSONTyped(value?: Occupancy | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'spaces': value['spaces'],
        'used': value['used'],
    };
}

