/* tslint:disable */
/* eslint-disable */
/**
 * GM-Owner API
 * OpenAPI-Spezifikation der owner-API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GmService
 */
export interface GmService {
    /**
     * name oder id des Service
     * @type {string}
     * @memberof GmService
     */
    name?: string;
    /**
     * url des Service
     * @type {string}
     * @memberof GmService
     */
    url?: string;
    /**
     * region des Service
     * @type {string}
     * @memberof GmService
     */
    region?: string;
    /**
     * version des Service
     * @type {string}
     * @memberof GmService
     */
    version?: string;
    /**
     * status des service
     * @type {boolean}
     * @memberof GmService
     */
    up?: boolean;
    /**
     * letzter positiver status check
     * @type {number}
     * @memberof GmService
     */
    lastUp?: number;
}

/**
 * Check if a given object implements the GmService interface.
 */
export function instanceOfGmService(value: object): value is GmService {
    return true;
}

export function GmServiceFromJSON(json: any): GmService {
    return GmServiceFromJSONTyped(json, false);
}

export function GmServiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): GmService {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'url': json['url'] == null ? undefined : json['url'],
        'region': json['region'] == null ? undefined : json['region'],
        'version': json['version'] == null ? undefined : json['version'],
        'up': json['up'] == null ? undefined : json['up'],
        'lastUp': json['lastUp'] == null ? undefined : json['lastUp'],
    };
}

  export function GmServiceToJSON(json: any): GmService {
      return GmServiceToJSONTyped(json, false);
  }

  export function GmServiceToJSONTyped(value?: GmService | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'url': value['url'],
        'region': value['region'],
        'version': value['version'],
        'up': value['up'],
        'lastUp': value['lastUp'],
    };
}

