/* tslint:disable */
/* eslint-disable */
/**
 * GM-Owner API
 * OpenAPI-Spezifikation der owner-API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GmService } from './GmService';
import {
    GmServiceFromJSON,
    GmServiceFromJSONTyped,
    GmServiceToJSON,
    GmServiceToJSONTyped,
} from './GmService';

/**
 * 
 * @export
 * @interface Services
 */
export interface Services {
    /**
     * 
     * @type {GmService}
     * @memberof Services
     */
    financeBackend?: GmService;
    /**
     * 
     * @type {GmService}
     * @memberof Services
     */
    propertyBackend?: GmService;
    /**
     * 
     * @type {GmService}
     * @memberof Services
     */
    parkingBackend?: GmService;
    /**
     * 
     * @type {GmService}
     * @memberof Services
     */
    paymentWatcher?: GmService;
    /**
     * 
     * @type {GmService}
     * @memberof Services
     */
    reportGenerationWorker?: GmService;
    /**
     * 
     * @type {GmService}
     * @memberof Services
     */
    managementFrontend?: GmService;
    /**
     * 
     * @type {GmService}
     * @memberof Services
     */
    parkingFrontend?: GmService;
    /**
     * 
     * @type {GmService}
     * @memberof Services
     */
    propertyDb?: GmService;
    /**
     * 
     * @type {GmService}
     * @memberof Services
     */
    parkingDb?: GmService;
    /**
     * 
     * @type {GmService}
     * @memberof Services
     */
    storage?: GmService;
}

/**
 * Check if a given object implements the Services interface.
 */
export function instanceOfServices(value: object): value is Services {
    return true;
}

export function ServicesFromJSON(json: any): Services {
    return ServicesFromJSONTyped(json, false);
}

export function ServicesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Services {
    if (json == null) {
        return json;
    }
    return {
        
        'financeBackend': json['finance-backend'] == null ? undefined : GmServiceFromJSON(json['finance-backend']),
        'propertyBackend': json['property-backend'] == null ? undefined : GmServiceFromJSON(json['property-backend']),
        'parkingBackend': json['parking-backend'] == null ? undefined : GmServiceFromJSON(json['parking-backend']),
        'paymentWatcher': json['payment-watcher'] == null ? undefined : GmServiceFromJSON(json['payment-watcher']),
        'reportGenerationWorker': json['report-generation-worker'] == null ? undefined : GmServiceFromJSON(json['report-generation-worker']),
        'managementFrontend': json['management-frontend'] == null ? undefined : GmServiceFromJSON(json['management-frontend']),
        'parkingFrontend': json['parking-frontend'] == null ? undefined : GmServiceFromJSON(json['parking-frontend']),
        'propertyDb': json['property-db'] == null ? undefined : GmServiceFromJSON(json['property-db']),
        'parkingDb': json['parking-db'] == null ? undefined : GmServiceFromJSON(json['parking-db']),
        'storage': json['storage'] == null ? undefined : GmServiceFromJSON(json['storage']),
    };
}

  export function ServicesToJSON(json: any): Services {
      return ServicesToJSONTyped(json, false);
  }

  export function ServicesToJSONTyped(value?: Services | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'finance-backend': GmServiceToJSON(value['financeBackend']),
        'property-backend': GmServiceToJSON(value['propertyBackend']),
        'parking-backend': GmServiceToJSON(value['parkingBackend']),
        'payment-watcher': GmServiceToJSON(value['paymentWatcher']),
        'report-generation-worker': GmServiceToJSON(value['reportGenerationWorker']),
        'management-frontend': GmServiceToJSON(value['managementFrontend']),
        'parking-frontend': GmServiceToJSON(value['parkingFrontend']),
        'property-db': GmServiceToJSON(value['propertyDb']),
        'parking-db': GmServiceToJSON(value['parkingDb']),
        'storage': GmServiceToJSON(value['storage']),
    };
}

