/* tslint:disable */
/* eslint-disable */
/**
 * GM-Owner API
 * OpenAPI-Spezifikation der owner-API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Services } from './Services';
import {
    ServicesFromJSON,
    ServicesFromJSONTyped,
    ServicesToJSON,
    ServicesToJSONTyped,
} from './Services';

/**
 * Tenant der Anwendung
 * @export
 * @interface Tenant
 */
export interface Tenant {
    /**
     * Id
     * @type {string}
     * @memberof Tenant
     */
    id?: string;
    /**
     * Die tenant-id im iam
     * @type {string}
     * @memberof Tenant
     */
    tenantId?: string;
    /**
     * Der Name des Tenant
     * @type {string}
     * @memberof Tenant
     */
    name?: string;
    /**
     * Abo Stufe des Tenant
     * @type {string}
     * @memberof Tenant
     */
    tier?: TenantTierEnum;
    /**
     * 
     * @type {Services}
     * @memberof Tenant
     */
    services?: Services;
    /**
     * 
     * @type {Services}
     * @memberof Tenant
     */
    customisation?: Services;
    /**
     * bevorzugte Region des Tenant
     * @type {string}
     * @memberof Tenant
     */
    preferedRegion?: string;
}


/**
 * @export
 */
export const TenantTierEnum = {
    Entry: 'Entry',
    Enhanced: 'Enhanced',
    Premium: 'Premium'
} as const;
export type TenantTierEnum = typeof TenantTierEnum[keyof typeof TenantTierEnum];


/**
 * Check if a given object implements the Tenant interface.
 */
export function instanceOfTenant(value: object): value is Tenant {
    return true;
}

export function TenantFromJSON(json: any): Tenant {
    return TenantFromJSONTyped(json, false);
}

export function TenantFromJSONTyped(json: any, ignoreDiscriminator: boolean): Tenant {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'tenantId': json['tenant-id'] == null ? undefined : json['tenant-id'],
        'name': json['name'] == null ? undefined : json['name'],
        'tier': json['tier'] == null ? undefined : json['tier'],
        'services': json['services'] == null ? undefined : ServicesFromJSON(json['services']),
        'customisation': json['customisation'] == null ? undefined : ServicesFromJSON(json['customisation']),
        'preferedRegion': json['prefered-region'] == null ? undefined : json['prefered-region'],
    };
}

  export function TenantToJSON(json: any): Tenant {
      return TenantToJSONTyped(json, false);
  }

  export function TenantToJSONTyped(value?: Tenant | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'tenant-id': value['tenantId'],
        'name': value['name'],
        'tier': value['tier'],
        'services': ServicesToJSON(value['services']),
        'customisation': ServicesToJSON(value['customisation']),
        'prefered-region': value['preferedRegion'],
    };
}

