/* tslint:disable */
/* eslint-disable */
/**
 * GM Properties API
 * OpenAPI-Spezifikation der GM Properties-API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GmTenant } from './GmTenant';
import {
    GmTenantFromJSON,
    GmTenantFromJSONTyped,
    GmTenantToJSON,
    GmTenantToJSONTyped,
} from './GmTenant';

/**
 * 
 * @export
 * @interface GmInfo
 */
export interface GmInfo {
    /**
     * 
     * @type {GmTenant}
     * @memberof GmInfo
     */
    tenant?: GmTenant;
}

/**
 * Check if a given object implements the GmInfo interface.
 */
export function instanceOfGmInfo(value: object): value is GmInfo {
    return true;
}

export function GmInfoFromJSON(json: any): GmInfo {
    return GmInfoFromJSONTyped(json, false);
}

export function GmInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GmInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'tenant': json['tenant'] == null ? undefined : GmTenantFromJSON(json['tenant']),
    };
}

  export function GmInfoToJSON(json: any): GmInfo {
      return GmInfoToJSONTyped(json, false);
  }

  export function GmInfoToJSONTyped(value?: GmInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tenant': GmTenantToJSON(value['tenant']),
    };
}

