/* tslint:disable */
/* eslint-disable */
/**
 * GM Properties API
 * OpenAPI-Spezifikation der GM Properties-API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FinanceReportMetadataFilters
 */
export interface FinanceReportMetadataFilters {
    /**
     * 
     * @type {string}
     * @memberof FinanceReportMetadataFilters
     */
    property?: string;
    /**
     * 
     * @type {Date}
     * @memberof FinanceReportMetadataFilters
     */
    startDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof FinanceReportMetadataFilters
     */
    endDate?: Date;
}

/**
 * Check if a given object implements the FinanceReportMetadataFilters interface.
 */
export function instanceOfFinanceReportMetadataFilters(value: object): value is FinanceReportMetadataFilters {
    return true;
}

export function FinanceReportMetadataFiltersFromJSON(json: any): FinanceReportMetadataFilters {
    return FinanceReportMetadataFiltersFromJSONTyped(json, false);
}

export function FinanceReportMetadataFiltersFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinanceReportMetadataFilters {
    if (json == null) {
        return json;
    }
    return {
        
        'property': json['property'] == null ? undefined : json['property'],
        'startDate': json['start_date'] == null ? undefined : (new Date(json['start_date'])),
        'endDate': json['end_date'] == null ? undefined : (new Date(json['end_date'])),
    };
}

  export function FinanceReportMetadataFiltersToJSON(json: any): FinanceReportMetadataFilters {
      return FinanceReportMetadataFiltersToJSONTyped(json, false);
  }

  export function FinanceReportMetadataFiltersToJSONTyped(value?: FinanceReportMetadataFilters | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'property': value['property'],
        'start_date': value['startDate'] == null ? undefined : ((value['startDate']).toISOString().substring(0,10)),
        'end_date': value['endDate'] == null ? undefined : ((value['endDate']).toISOString().substring(0,10)),
    };
}

