/* tslint:disable */
/* eslint-disable */
/**
 * GM Properties API
 * OpenAPI-Spezifikation der GM Properties-API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FinanceReportMetadataFilters } from './FinanceReportMetadataFilters';
import {
    FinanceReportMetadataFiltersFromJSON,
    FinanceReportMetadataFiltersFromJSONTyped,
    FinanceReportMetadataFiltersToJSON,
    FinanceReportMetadataFiltersToJSONTyped,
} from './FinanceReportMetadataFilters';

/**
 * 
 * @export
 * @interface FinanceReportMetadata
 */
export interface FinanceReportMetadata {
    /**
     * 
     * @type {Date}
     * @memberof FinanceReportMetadata
     */
    generatedAt?: Date;
    /**
     * 
     * @type {FinanceReportMetadataFilters}
     * @memberof FinanceReportMetadata
     */
    filters?: FinanceReportMetadataFilters;
}

/**
 * Check if a given object implements the FinanceReportMetadata interface.
 */
export function instanceOfFinanceReportMetadata(value: object): value is FinanceReportMetadata {
    return true;
}

export function FinanceReportMetadataFromJSON(json: any): FinanceReportMetadata {
    return FinanceReportMetadataFromJSONTyped(json, false);
}

export function FinanceReportMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinanceReportMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'generatedAt': json['generated_at'] == null ? undefined : (new Date(json['generated_at'])),
        'filters': json['filters'] == null ? undefined : FinanceReportMetadataFiltersFromJSON(json['filters']),
    };
}

  export function FinanceReportMetadataToJSON(json: any): FinanceReportMetadata {
      return FinanceReportMetadataToJSONTyped(json, false);
  }

  export function FinanceReportMetadataToJSONTyped(value?: FinanceReportMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'generated_at': value['generatedAt'] == null ? undefined : ((value['generatedAt']).toISOString()),
        'filters': FinanceReportMetadataFiltersToJSON(value['filters']),
    };
}

