apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.propertyBackend.name }}
  labels:
    app: {{ .Values.propertyBackend.name }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.propertyBackend.containerPort }}
  selector:
    app: {{ .Values.propertyBackend.name }}
