{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: staging-ingress
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - http:
        paths:
          {{- range .Values.microservices }}
          - path: {{ .ingressPath }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ .name }}
                port:
                  number: {{ .containerPort }}
          {{- end }}
{{- end }}
