apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.managementFrontend.name }}
  labels:
    app: {{ .Values.managementFrontend.name }}
spec:
  replicas: {{ .Values.managementFrontend.replicaCount }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Values.managementFrontend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.managementFrontend.name }}
    spec:
      serviceAccountName: staging
      containers:
        - name: {{ .Values.managementFrontend.name }}
          image: "{{ .Values.managementFrontend.artifactRegistryPath }}/{{ .Values.managementFrontend.image }}:{{ .Values.managementFrontend.version }}"
          ports:
            - containerPort: {{ .Values.managementFrontend.containerPort }}
          readinessProbe:
            httpGet:
              path: {{ .Values.managementFrontend.readinessProbePath }}
              port: {{ .Values.managementFrontend.containerPort }}
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: {{ .Values.managementFrontend.readinessProbePath }}
              port: {{ .Values.managementFrontend.containerPort }}
            initialDelaySeconds: 30
            periodSeconds: 15
