/* tslint:disable */
/* eslint-disable */
/**
 * GM Properties API
 * OpenAPI-Spezifikation der GM Properties-API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  GenerateViewFinanceReport200Response,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    GenerateViewFinanceReport200ResponseFromJSON,
    GenerateViewFinanceReport200ResponseToJSON,
} from '../models/index';

export interface ExportDataRequest {
    property?: string;
    startDate?: Date;
    endDate?: Date;
}

export interface GenerateDefectReportRequest {
    property: string;
    status?: string;
    startDate?: string;
    endDate?: string;
}

export interface GenerateViewFinanceReportRequest {
    reportType: GenerateViewFinanceReportReportTypeEnum;
    property?: string;
    startDate?: Date;
    endDate?: Date;
}

/**
 * 
 */
export class FinanceApi extends runtime.BaseAPI {

    /**
     * Gibt alle Rohdaten zurück. Optional kann nach Datum und Property gefiltert werden. Die Daten werden im CSV-Format zurückgegeben.
     * Rohdaten ausgeben
     */
    async exportDataRaw(requestParameters: ExportDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        const queryParameters: any = {};

        if (requestParameters['property'] != null) {
            queryParameters['property'] = requestParameters['property'];
        }

        if (requestParameters['startDate'] != null) {
            queryParameters['start_date'] = (requestParameters['startDate'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['endDate'] != null) {
            queryParameters['end_date'] = (requestParameters['endDate'] as any).toISOString().substring(0,10);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/finance/exportdata`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Gibt alle Rohdaten zurück. Optional kann nach Datum und Property gefiltert werden. Die Daten werden im CSV-Format zurückgegeben.
     * Rohdaten ausgeben
     */
    async exportData(requestParameters: ExportDataRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.exportDataRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Erstellt und exportiert einen Report über Defekte, basierend auf den vorhandenen Daten. Der Report wird in der Cloud gespeichert, und ein Link wird zurückgegeben.
     * Defect-Report generieren und exportieren
     */
    async generateDefectReportRaw(requestParameters: GenerateDefectReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['property'] == null) {
            throw new runtime.RequiredError(
                'property',
                'Required parameter "property" was null or undefined when calling generateDefectReport().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['property'] != null) {
            queryParameters['property'] = requestParameters['property'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['startDate'] != null) {
            queryParameters['start_date'] = requestParameters['startDate'];
        }

        if (requestParameters['endDate'] != null) {
            queryParameters['end_date'] = requestParameters['endDate'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/finance/defectreport`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Erstellt und exportiert einen Report über Defekte, basierend auf den vorhandenen Daten. Der Report wird in der Cloud gespeichert, und ein Link wird zurückgegeben.
     * Defect-Report generieren und exportieren
     */
    async generateDefectReport(requestParameters: GenerateDefectReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.generateDefectReportRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Erstellt und exportiert entweder einen Revenue- oder Profit-Report basierend auf den angegebenen Parametern.
     * Generiere einen Finanz-Bericht (Revenue oder Profit)
     */
    async generateViewFinanceReportRaw(requestParameters: GenerateViewFinanceReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GenerateViewFinanceReport200Response>> {
        if (requestParameters['reportType'] == null) {
            throw new runtime.RequiredError(
                'reportType',
                'Required parameter "reportType" was null or undefined when calling generateViewFinanceReport().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['reportType'] != null) {
            queryParameters['report_type'] = requestParameters['reportType'];
        }

        if (requestParameters['property'] != null) {
            queryParameters['property'] = requestParameters['property'];
        }

        if (requestParameters['startDate'] != null) {
            queryParameters['start_date'] = (requestParameters['startDate'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['endDate'] != null) {
            queryParameters['end_date'] = (requestParameters['endDate'] as any).toISOString().substring(0,10);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/finance/financereport`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GenerateViewFinanceReport200ResponseFromJSON(jsonValue));
    }

    /**
     * Erstellt und exportiert entweder einen Revenue- oder Profit-Report basierend auf den angegebenen Parametern.
     * Generiere einen Finanz-Bericht (Revenue oder Profit)
     */
    async generateViewFinanceReport(requestParameters: GenerateViewFinanceReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GenerateViewFinanceReport200Response> {
        const response = await this.generateViewFinanceReportRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GenerateViewFinanceReportReportTypeEnum = {
    Revenue: 'revenue',
    Profit: 'profit'
} as const;
export type GenerateViewFinanceReportReportTypeEnum = typeof GenerateViewFinanceReportReportTypeEnum[keyof typeof GenerateViewFinanceReportReportTypeEnum];
