name: Deploy Staging

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B clean package -Pdev --file property-backend/pom.xml
      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: property-backend-jar
          path: property-backend/target/*.jar

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download JAR Artifact
        uses: actions/download-artifact@v3
        with:
          name: property-backend-jar
          path: ./property-backend/target
      - name: Create .env file
        run: |
          echo "NEXT_PUBLIC_BASE_PATH=${{ vars.STAGING_BASE_PATH }}" > property-frontend/.env.production
          echo "NEXT_PUBLIC_APPLICATION_NAME=${{ vars.STAGING_APPLICATION_NAME }}" >> property-frontend/.env.production
          echo "NEXT_PUBLIC_FIREBASE_API_KEY=${{ secrets.FIREBASE_KEY }}" >> property-frontend/.env.production
          echo "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_DOMAIN}}" >> property-frontend/.env.production
      - name: Build Backend
        run: |
          docker build -t com/group/property-backend-staging ./property-backend
          docker tag com/group/property-backend-staging europe-west1-docker.pkg.dev/ca-test2-438111/cloud-run-source-deploy/com/group/property-backend-staging
      - name: Build property-frontend
        run: |
          docker build -t com/group/property-frontend-staging ./property-frontend
          docker tag com/group/property-frontend-staging europe-west1-docker.pkg.dev/ca-test2-438111/cloud-run-source-deploy/com/group/property-frontend-staging
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: ca-test2-438111
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Configure Docker to use gcloud credentials
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev
          gcloud config set project ca-test2-438111
      - name: Push Bakend image to GCR
        run: |
          docker push europe-west1-docker.pkg.dev/ca-test2-438111/cloud-run-source-deploy/com/group/property-backend-staging
      - name: Push property-frontend image to GCR
        run: |
          docker push europe-west1-docker.pkg.dev/ca-test2-438111/cloud-run-source-deploy/com/group/property-frontend-staging

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - name: Authenticate to Google Cloud
       uses: google-github-actions/auth@v2
       with:
          project_id: ca-test2-438111
          credentials_json: ${{ secrets.GCP_SA_KEY }}
     - name: Configure Docker to use gcloud credentials
       run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev
          gcloud config set project ca-test2-438111
     - name: Deploy Backend to Cloud Run
       run: |
          gcloud run deploy property-backend-staging --image=europe-west1-docker.pkg.dev/ca-test2-438111/cloud-run-source-deploy/com/group/property-backend-staging --platform=managed --region=europe-west1 --allow-unauthenticated --port=8081 --memory=1Gi --service-account ${{ secrets.DEV_SERVICEACCOUNT }} --set-env-vars "SPRING_PROFILES_ACTIVE=dev"
     - name: Deploy property-frontend to Cloud Run
       run: |
          gcloud run deploy property-frontend-staging --image=europe-west1-docker.pkg.dev/ca-test2-438111/cloud-run-source-deploy/com/group/property-frontend-staging --platform=managed --region=europe-west1 --allow-unauthenticated --port=8081 --memory=1Gi --service-account ${{ secrets.DEV_SERVICEACCOUNT }} --set-env-vars "SPRING_PROFILES_ACTIVE=dev"
