name: Deploy Finance-Backend

on:
  push:
    branches: ["dev"]
    paths:
      - "finance-backend/**"
  pull_request:
    branches: ["dev"]
    paths:
      - "finance-backend/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Read versions from version.yaml
        id: read_versions
        run: |
          VERSION_FINANCE=$(yq eval '.finance-backend' finance-backend/version.yaml)
          echo "VERSION_FINANCE=$VERSION_FINANCE" >> $GITHUB_ENV
      - name: Build finance with Maven
        run: mvn -B clean package -Pdev --file finance-backend/pom.xml
      - name: Upload Finance JAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: finance-backend-jar
          path: finance-backend/target/*.jar

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read versions from version.yaml
        id: read_versions
        run: |
          VERSION_FINANCE=$(yq eval '.finance-backend' finance-backend/version.yaml)
          echo "VERSION_FINANCE=$VERSION_FINANCE" >> $GITHUB_ENV
      - name: Download Finance JAR Artifact
        uses: actions/download-artifact@v3
        with:
          name: finance-backend-jar
          path: ./finance-backend/target
      - name: Build Finance Backend
        run: |
          docker build -t com/group/finance-backend:${{ env.VERSION_FINANCE }} ./finance-backend
          docker tag com/group/finance-backend:${{ env.VERSION_FINANCE }} europe-west1-docker.pkg.dev/ca-test2-438111/cloud-run-source-deploy/com/group/finance-backend:${{ env.VERSION_FINANCE }}
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: ca-test2-438111
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker to use gcloud credentials
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev
          gcloud config set project ca-test2-438111

      - name: Push backend images to GCR
        run: |
          docker push europe-west1-docker.pkg.dev/ca-test2-438111/cloud-run-source-deploy/com/group/finance-backend:${{ env.VERSION_FINANCE }}