name: Java CI with Maven

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B clean package --file gm-backend/pom.xml  # Nutzt "package" anstelle von "install"
      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: gm-backend-jar
          path: gm-backend/target/*.jar  # Passe den Pfad an, falls das JAR anders benannt ist

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Download JAR Artifact
        uses: actions/download-artifact@v3
        with:
          name: gm-backend-jar
          path: ./gm-backend/target
      - name: Build the Docker image
        run: |
          docker build -t com/group/gm-backend-prod ./gm-backend  # Ersetze 'YOUR_PROJECT_ID' mit deiner Google Cloud Projekt-ID
          docker tag com/group/gm-backend-prod europe-west1-docker.pkg.dev/ca-test2-438111/cloud-run-source-deploy/com/group/gm-backend-prod  # Tagging des Images
      - name: Authenticate to Google Cloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ca-test2-438111  # Ersetze 'YOUR_PROJECT_ID' mit deiner Google Cloud Projekt-ID
          service_account_key: ${{ secrets.GCP_SA_KEY }}  # F端ge deinen Service Account Schl端ssel in die GitHub Secrets ein
      - name: Push Docker image to GCR
        run: |
          docker push europe-west1-docker.pkg.dev/ca-test2-438111/cloud-run-source-deploy/com/group/gm-backend-prod  # Push des getaggten Images

  deploy:
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ca-test2-438111  # Ersetze 'YOUR_PROJECT_ID' mit deiner Google Cloud Projekt-ID
          service_account_key: ${{ secrets.GCP_SA_KEY }}  # F端ge deinen Service Account Schl端ssel in die GitHub Secrets ein
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy gm-backend-prod --image=europe-west1-docker.pkg.dev/ca-test2-438111/cloud-run-source-deploy/com/group/gm-backend-prod --platform=managed --region=europe-west1 --allow-unauthenticated --port=8081 --memory=1Gi --set-env-vars "SPRING_PROFILES_ACTIVE=dev"
