name: gm-deploy-prod

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B clean package --file gm-backend/pom.xml  # Nutzt "package" anstelle von "install"
      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: gm-backend-jar
          path: gm-backend/target/*.jar  # Passe den Pfad an, falls das JAR anders benannt ist

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Download JAR Artifact
        uses: actions/download-artifact@v3
        with:
          name: gm-backend-jar
          path: ./gm-backend/target
      - name: Build the Docker image
        run: docker build -t com/group/gm-backend ./gm-backend  # Nutzt den Ordner "gm-backend" als Kontext
