name: Deploy Prod

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
#   build:
#     runs-on: ubuntu-latest
# 
#     steps:
#       - uses: actions/checkout@v4
#       - name: Set up JDK 21
#         uses: actions/setup-java@v4
#         with:
#           java-version: '21'
#           distribution: 'temurin'
#           cache: maven
#       - name: Build with Maven
#         run: mvn -B clean package --file gm-backend/pom.xml  # Nutzt "package" anstelle von "install"
#       - name: Upload JAR Artifact
#         uses: actions/upload-artifact@v3
#         with:
#           name: gm-backend-jar
#           path: gm-backend/target/*.jar  # Passe den Pfad an, falls das JAR anders benannt ist

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      #- name: Download JAR Artifact
      #  uses: actions/download-artifact@v3
      #  with:
      #    name: gm-backend-jar
      #    path: ./gm-backend/target
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_REACT_APP_BASE_PATH: ${{ secrets.PROD_BASE_PATH }}
      # - name: Build Backend
      #   run: |
      #     docker build -t com/group/gm-backend-prod ./gm-backend
      #     docker tag com/group/gm-backend-prod europe-west1-docker.pkg.dev/ca-test2-438111/cloud-run-source-deploy/com/group/gm-backend-prod
      - name: Build Frontend
        run: |
          docker build -t com/group/gm-frontend-prod ./frontend
          docker tag com/group/gm-frontend-prod europe-west1-docker.pkg.dev/ca-test2-438111/cloud-run-source-deploy/com/group/gm-frontend-prod
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: ca-test2-438111
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Configure Docker to use gcloud credentials
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev
          gcloud config set project ca-test2-438111
      #- name: Push Bakend image to GCR
      #  run: |
      #    docker push europe-west1-docker.pkg.dev/ca-test2-438111/cloud-run-source-deploy/com/group/gm-backend-prod
      - name: Push Frontend image to GCR
        run: |
          docker push europe-west1-docker.pkg.dev/ca-test2-438111/cloud-run-source-deploy/com/group/gm-frontend-prod

  deploy:
    needs: docker
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v4
     - name: Authenticate to Google Cloud
       uses: google-github-actions/auth@v2
       with:
          project_id: ca-test2-438111
          credentials_json: ${{ secrets.GCP_SA_KEY }}
     - name: Configure Docker to use gcloud credentials
       run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev
          gcloud config set project ca-test2-438111
     # - name: Deploy Backend to Cloud Run
     #   run: |
     #      gcloud run deploy gm-backend-prod --image=europe-west1-docker.pkg.dev/ca-test2-438111/cloud-run-source-deploy/com/group/gm-backend-prod --platform=managed --region=europe-west1 --allow-unauthenticated --port=8081 --memory=1Gi --set-env-vars "SPRING_PROFILES_ACTIVE=dev"
     - name: Deploy Frontend to Cloud Run
       run: |
          gcloud run deploy gm-frontend-prod --image=europe-west1-docker.pkg.dev/ca-test2-438111/cloud-run-source-deploy/com/group/gm-frontend-prod --platform=managed --region=europe-west1 --allow-unauthenticated --port=8081 --memory=1Gi --set-env-vars "SPRING_PROFILES_ACTIVE=dev"