name: Deploy property-backend

on:
  push:
    branches: ["dev"]
    paths:
      - "property-backend/**"
  pull_request:
    branches: ["dev"]
    paths:
      - "property-backend/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Read versions from version.yaml
        id: read_versions
        run: |
          VERSION_PROPERTY=$(yq eval '.property-backend' property-backend/version.yaml)
          echo "VERSION_PROPERTY=$VERSION_PROPERTY" >> $GITHUB_ENV

      - name: Build Property with Maven
        run: mvn -B clean package -Pdev --file property-backend/pom.xml

      - name: Upload Property JAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: property-backend-jar
          path: property-backend/target/*.jar

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read versions from version.yaml
        id: read_versions
        run: |
          VERSION_PROPERTY=$(yq eval '.property-backend' property-backend/version.yaml)
          echo "VERSION_PROPERTY=$VERSION_PROPERTY" >> $GITHUB_ENV

      - name: Download Property JAR Artifact
        uses: actions/download-artifact@v3
        with:
          name: property-backend-jar
          path: ./property-backend/target

      - name: Build Property Backend
        run: |
          docker build -t com/group/property-backend:${{ env.VERSION_PROPERTY }} ./property-backend
          docker tag com/group/property-backend:${{ env.VERSION_PROPERTY }} europe-west1-docker.pkg.dev/ca-test2-438111/cloud-run-source-deploy/com/group/property-backend:${{ env.VERSION_PROPERTY }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: ca-test2-438111
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker to use gcloud credentials
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev
          gcloud config set project ca-test2-438111

      - name: Push image to GCR
        run: |
          docker push europe-west1-docker.pkg.dev/ca-test2-438111/cloud-run-source-deploy/com/group/property-backend:${{ env.VERSION_PROPERTY }}